/*-------------------------------------------------Llaves Foraneas--------------------------------------------------------------*/

ALTER TABLE NUTRITEC.ALUMNOS ADD CONSTRAINT IALUMNO1 FOREIGN KEY (CARRERA_ID) REFERENCES NUTRITEC.CARRERAS(CARRERA_ID);

ALTER TABLE NUTRITEC.ALUMNOS ADD CONSTRAINT IALUMNO2 FOREIGN KEY (MATERIA_ID) REFERENCES NUTRITEC.MATERIAS(MATERIA_ID);

ALTER TABLE NUTRITEC.CLINICAS_TURNOS ADD CONSTRAINT ICLINICA1 FOREIGN KEY (CLINICA_ID) REFERENCES NUTRITEC.CLINICAS(CLINICA_ID);

ALTER TABLE NUTRITEC.ASIGNACIONES ADD CONSTRAINT IASIGNACION1 FOREIGN KEY (CLINICA_ID) REFERENCES NUTRITEC.CLINICAS(CLINICA_ID);

ALTER TABLE NUTRITEC.ASIGNACIONES ADD CONSTRAINT IASIGNACION2 FOREIGN KEY (ALUMNO_ID) REFERENCES NUTRITEC.ALUMNOS(ALUMNO_ID);

/*Llaves del sistema*/
ALTER TABLE NUTRITEC.auth_group_permissions ADD CONSTRAINT IAUTH_GROUP_PERMISSION1 FOREIGN KEY (permission_id) REFERENCES NUTRITEC.auth_permission(id);

ALTER TABLE NUTRITEC.auth_group_permissions ADD CONSTRAINT IAUTH_GROUP_PERMISSION2 FOREIGN KEY (group_id) REFERENCES NUTRITEC.auth_group(id);

ALTER TABLE NUTRITEC.auth_permission ADD CONSTRAINT IAUTH_PERMISSION1 FOREIGN KEY (content_type_id) REFERENCES NUTRITEC.django_content_type(id);

ALTER TABLE NUTRITEC.auth_user_groups ADD CONSTRAINT IAUTH_USER_GROUPS1 FOREIGN KEY (group_id) REFERENCES NUTRITEC.auth_group(id);

ALTER TABLE NUTRITEC.auth_user_groups ADD CONSTRAINT IAUTH_USER_GROUPS2 FOREIGN KEY (user_id) REFERENCES NUTRITEC.auth_user(id);

ALTER TABLE NUTRITEC.auth_user_user_permissions ADD CONSTRAINT IAUTH_USER_USER_PERMISSION1 FOREIGN KEY (permission_id) REFERENCES NUTRITEC.auth_permission(id);

ALTER TABLE NUTRITEC.auth_user_user_permissions ADD CONSTRAINT IAUTH_USER_USER_PERMISSION2 FOREIGN KEY (user_id) REFERENCES NUTRITEC.auth_user(id);

ALTER TABLE NUTRITEC.django_admin_log ADD  CONSTRAINT IDJANGO_ADMIN_LOG1 FOREIGN KEY (content_type_id) REFERENCES NUTRITEC.django_content_type(id);

ALTER TABLE NUTRITEC.django_admin_log ADD  CONSTRAINT IDJANGO_ADMIN_LOG2 FOREIGN KEY (user_id) REFERENCES NUTRITEC.auth_user(id);

ALTER TABLE NUTRITEC.ROLES ADD CONSTRAINT IROL1 FOREIGN KEY (USUARIO_ID) REFERENCES NUTRITEC.auth_user(id);

